version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: school-major
    environment:
      POSTGRES_DB: Database
      POSTGRES_USER: User
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:  
    image: school-major-api  # ใช้ชื่อ image ของ Spring Boot app ที่ build แล้ว
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Database
      SPRING_DATASOURCE_USERNAME: User
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
